import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Loading from './loading'
import LeftMenu from '@/components/LeftMenu/LeftMenu'
import { Suspense, useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Healthy Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-row">
          <div className="left-nav-menu-bar w-12 lg:w-72 overflow-y-auto">
            <LeftMenu />
          </div>
          <div className="w-full overflow-y-auto">
            <Suspense fallback={<Loading />}>
              {children}
            </Suspense>
          </div>
        </div>
      </body>
    </html>
  )
}
